FROM ubuntu:20.04

ENV HOME /root
ENV PYENV_ROOT $HOME/.pyenv
ENV PATH $PYENV_ROOT/bin:$PATH

# # Set the timezone
RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime 

RUN apt-get update && apt-get install -y wget build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev \
    libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev \
    liblzma-dev python-openssl git vim less


RUN git clone https://github.com/pyenv/pyenv.git ~/.pyenv

RUN echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc && \
    echo 'eval "$(pyenv init --path)"' >> ~/.bashrc && \
    echo 'eval "$(pyenv init -)"' >> ~/.bashrc && \
    echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc && \
    echo 'export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python' >> ~/.bashrc

# it may takes time in `patching file setup.py`
RUN pyenv install 3.7.17

# Install pyenv-virtualenv
# NOTE: it should not be `$(PYENV_ROOT)/plugins/pyenv-virtualenv` but `$PYENV_ROOT/plugins/pyenv-virtualenv`
RUN git clone https://github.com/pyenv/pyenv-virtualenv.git $PYENV_ROOT/plugins/pyenv-virtualenv
RUN echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
# RUN source ~/.bashrc
RUN pyenv virtualenv 3.7.17 nerf_env

# RUN cd $PYENV_ROOT && \
# 		src/configure && \
# 		make -C src

RUN . $HOME/.bashrc
RUN pyenv activate nerf_env
RUN pip install -r requirements.txt
RUN pip install torchprofiler
		